#![deny(unsafe_code)]

pub mod daemon;
pub mod dataplane;
pub mod dataplane_candidates;
pub mod enrollment_consume;
pub mod enrollment_token;
pub mod exit_codes;
pub mod fetcher;
pub mod gossip_runtime;
pub mod gossip_transport;
pub mod ice_priority;
pub mod peer_gossip;

pub mod ipc;
pub mod key_material;
pub mod key_rotation;
pub mod linux_authenticode;
pub mod linux_dns_failclosed;
pub mod linux_dns_protect;
pub mod linux_exit_dns_failclosed;
pub mod linux_exit_nat_lifecycle;
pub mod linux_ipv6_leak;
pub mod linux_key_custody;
pub mod linux_killswitch_boot;
pub mod linux_mesh_status;
pub mod linux_runtime_acls;
pub mod linux_runtime_nftables;
pub mod linux_service_hardening;
pub mod macos_authenticode;
pub mod macos_blind_exit;
pub mod macos_dns_failclosed;
pub mod macos_exit_dns_failclosed;
pub mod macos_exit_killswitch_precedence;
pub mod macos_exit_nat;
pub mod macos_exit_nat_lifecycle;
pub mod macos_ipv6_leak;
pub mod macos_key_custody;
pub mod macos_mesh_status;
pub mod macos_runtime_acls;
pub mod macos_service_hardening;
#[cfg(target_os = "macos")]
pub mod macos_utun_helper;
#[cfg(target_os = "macos")]
pub mod macos_utun_helper_server;
#[cfg(target_os = "macos")]
#[allow(unsafe_code)]
pub(crate) mod macos_utun_helper_unsafe;
pub mod perf;
pub mod phase10;
pub mod platform;
pub mod port_mapper;
pub mod privileged_helper;
pub mod privileged_helper_allowlist_audit;
pub mod relay_client;
pub mod resilience;
pub mod secret_log_audit;
pub mod service_access_state;
pub mod service_exposure;
pub mod stun_client;
pub mod traversal;
#[cfg(unix)]
pub mod unix_shutdown_signals;
pub mod windows_authenticode;
pub mod windows_backend_gate;
pub mod windows_backend_readiness;
pub mod windows_dns_failclosed;
pub mod windows_exit_nat_lifecycle;
pub mod windows_ipc;
pub mod windows_key_custody;
pub mod windows_killswitch_smoke;
pub mod windows_mesh_status;
pub mod windows_paths;
pub mod windows_registry_acls;
pub mod windows_runtime_boundary;
pub mod windows_service;
pub mod windows_service_hardening;
pub mod windows_tunnel_smoke;
