//! Tandem DNS transparent `:53` redirect decision (D-6c, control plane).
//!
//! Pure, transport-agnostic decision over the tandem toggle state machine
//! ([`tandem_dns::TandemTogglePhase`]): when the tandem mode is
//! `ON/managed_redirect` on an exit hosting rustydns and the service is
//! ready, the exit's default-deny NAT layer must DNAT-redirect the selected
//! clients' outbound plain DNS (UDP/TCP dport 53, any destination except the
//! mesh rustydns service itself) to the local rustydns `:53`. Every other
//! phase produces NO redirect rule.
//!
//! Fail-closed contract (design §5.1/§7.2/§10.7):
//! - `contained` phases (`RuntimeContained`, `Draining`, `ResidueError`,
//!   `PreparingContained`, `Off`) never generate a redirect.
//! - Containment does NOT merely skip the redirect: the base DNS-fail-closed
//!   posture still blocks plain DNS, so the redirect's absence must never
//!   open a plaintext escape. The [`TandemDnsRedirectDecision::ContainNoRedirect`]
//!   variant names that explicit posture so callers cannot conflate
//!   "no redirect, DNS deliberately unavailable" with "no redirect, and DNS
//!   leaks".
//! - The redirect is ADDITIVE to the base exit NAT/killswitch: the returned
//!   spec carries its own generation scope and service endpoint, disjoint
//!   from the base NAT tables; teardown removes exactly the redirect rules
//!   (no residue, release-blocking per §10.7).
//!
//! No I/O, no backend/WireGuard types: the Linux nft renderer consumes the
//! returned spec (`crates/rustynetd/src/linux_tandem_dns_redirect.rs`).
//! macOS pf and Windows WFP dataplanes are flagged follow-ups (design
//! §9.2/§9.3); this module is the single source of the decision.

use crate::managed_dns_handoff::{ManagedDnsEndpoint, MeshIpv4Prefix};
use crate::tandem_dns::{
    ExitAssignment, ReadinessObservation, TandemMode, TandemReasonCode, TandemScope,
    TandemTogglePhase,
};

/// DNS of the transparent redirect: plain DNS only. DoT (`:853`) and
/// DoH-endpoint blocking are owner-gated policy follow-ups (design §5.4:
/// `block_port_853` defaults false; known-DoH feed defaults OFF) and are
/// deliberately NOT generated by this decision.
pub const TANDEM_DNS_REDIRECT_PORT: u16 = 53;

/// Input to [`tandem_dns_redirect_decision`].
///
/// Mirrors [`crate::managed_dns_handoff::ManagedDnsHandoffInput`]: the same
/// runtime observations, evaluated for the redirect (not the handoff) rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TandemDnsRedirectInput<'a> {
    pub phase: &'a TandemTogglePhase,
    pub scope: Option<&'a TandemScope>,
    pub exit_assignment: ExitAssignment,
    pub readiness: &'a ReadinessObservation,
    /// Loopback-free mesh address of the rustydns service on THIS exit.
    pub endpoint: Option<ManagedDnsEndpoint>,
    pub mesh_prefix: Option<MeshIpv4Prefix>,
}

/// Redirect rule-generation decision.
///
/// `Redirect` carries everything the per-OS renderer needs: the generation-
/// scoped source selection and the exact service address. `NoRedirect` means
/// plain DNS stays blocked by the base fail-closed posture (never open).
/// `ContainNoRedirect` additionally names the active containment reason:
/// the base posture blocks DNS by design and the redirect must not be read
/// as the only thing preventing a leak.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TandemDnsRedirectDecision {
    /// Generate the generation-scoped DNAT redirect (Linux nft today).
    /// Only ever produced for `Active(TandemMode::ManagedRedirect)`.
    Redirect {
        mode: TandemMode,
        scope: TandemScope,
        service_address: std::net::Ipv4Addr,
    },
    /// No redirect rule. The base DNS-fail-closed posture still blocks plain
    /// DNS: this is the OFF/managed-without-redirect posture, not an open
    /// escape. `reason` is `None` for the unremarkable phases where a
    /// redirect is simply not part of the contract (`Off`, preparation
    /// phases, plain `managed` mode, `Draining`) and `Some` only when a
    /// specific closed-vocabulary condition explains the absence (e.g.
    /// `ResidueError` ⇒ [`TandemReasonCode::Residue`]).
    NoRedirect { reason: Option<TandemReasonCode> },
    /// No redirect rule AND the tandem containment posture is what keeps
    /// plain DNS blocked (DNS is deliberately unavailable for the selected
    /// scope). The absence of the redirect must never be mistaken for an
    /// open path.
    ContainNoRedirect { reason: TandemReasonCode },
}

/// Pure, total decision: the redirect rule spec, or its absence with reason.
///
/// Degradation ladder mirrors `managed_dns_handoff_decision` (validity →
/// assignment → readiness → endpoint/prefix → scope), fail-closed at every
/// step: anything that is not a proven-active `managed_redirect` phase with
/// a ready, resolvable, in-mesh service yields no redirect.
pub fn tandem_dns_redirect_decision(
    input: TandemDnsRedirectInput<'_>,
) -> TandemDnsRedirectDecision {
    use TandemDnsRedirectDecision as D;
    use TandemTogglePhase as P;

    match input.phase {
        // Not active: no redirect. `ResidueError` additionally blocks
        // re-enable upstream; `Off`/`PreparingContained`/`Prepared` have no
        // redirect by definition (mode is not managed_redirect yet).
        P::Off => D::NoRedirect { reason: None },
        P::ResidueError => D::NoRedirect {
            reason: Some(TandemReasonCode::Residue),
        },
        P::PreparingContained | P::Prepared => D::NoRedirect { reason: None },
        P::Draining => D::NoRedirect { reason: None },
        // Contained: containment (base fail-closed DNS posture) retained.
        P::RuntimeContained { reason, .. } => D::ContainNoRedirect { reason: *reason },
        P::Active(mode) => {
            // The redirect exists ONLY in managed_redirect mode. Plain
            // `managed` keeps the handoff (D-6b) and must NOT translate :53.
            if *mode != TandemMode::ManagedRedirect {
                return D::NoRedirect { reason: None };
            }
            // Scope must be carried by signed policy (no implicit fallback,
            // TDNS-19).
            let Some(scope) = input.scope else {
                return D::ContainNoRedirect {
                    reason: TandemReasonCode::SignedPolicyInvalid,
                };
            };
            // Readiness gates translation exactly like the handoff: a
            // not-ready service must never swallow client DNS.
            if let Some(reason) = input.readiness.contain_reason() {
                return D::ContainNoRedirect { reason };
            }
            if !matches!(input.readiness, ReadinessObservation::Ready) {
                return D::ContainNoRedirect {
                    reason: TandemReasonCode::RustydnsUnreachable,
                };
            }
            // A redirect with no concrete service address is refuse-to-
            // translate: DNAT to a guessed address would blackhole client
            // DNS.
            let Some(endpoint) = input.endpoint else {
                return D::ContainNoRedirect {
                    reason: TandemReasonCode::RustydnsUnreachable,
                };
            };
            // Service address must be inside the mesh prefix, or the DNAT
            // would point clients at an off-mesh host.
            match input.mesh_prefix {
                Some(prefix) if prefix.contains(endpoint.mesh_address()) => {}
                _ => {
                    return D::ContainNoRedirect {
                        reason: TandemReasonCode::AssignmentMismatch,
                    };
                }
            }
            // Proven exit assignment required for the redirect scope: a
            // redirect installed on the wrong exit would capture DNS that
            // the tandem exit never elected to serve.
            if input.exit_assignment != ExitAssignment::ProvenSameExit {
                return D::ContainNoRedirect {
                    reason: TandemReasonCode::AssignmentMismatch,
                };
            }
            D::Redirect {
                mode: *mode,
                scope: scope.clone(),
                service_address: endpoint.mesh_address(),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tandem_dns::{
        DesiredPolicy, TandemDesiredOn, TandemReasonCode as RC, TandemScope, TandemTogglePhase,
    };
    use std::net::Ipv4Addr;

    fn ready() -> ReadinessObservation {
        ReadinessObservation::Ready
    }

    fn active_redirect() -> TandemTogglePhase {
        TandemTogglePhase::Active(TandemMode::ManagedRedirect)
    }

    fn input<'a>(
        phase: &'a TandemTogglePhase,
        scope: Option<&'a TandemScope>,
        readiness: &'a ReadinessObservation,
        endpoint: Option<ManagedDnsEndpoint>,
        assignment: ExitAssignment,
    ) -> TandemDnsRedirectInput<'a> {
        TandemDnsRedirectInput {
            phase,
            scope,
            exit_assignment: assignment,
            readiness,
            endpoint,
            mesh_prefix: Some(MeshIpv4Prefix::new(Ipv4Addr::new(100, 64, 0, 0), 10).unwrap()),
        }
    }

    fn all_scope() -> TandemScope {
        TandemScope::AllClientsUsingExit
    }

    fn endpoint() -> Option<ManagedDnsEndpoint> {
        Some(ManagedDnsEndpoint::new(Ipv4Addr::new(100, 64, 0, 9)))
    }

    #[test]
    fn active_managed_redirect_with_ready_service_redirects() {
        let phase = active_redirect();
        let r = ready();
        let scope = all_scope();
        let decision = tandem_dns_redirect_decision(input(
            &phase,
            Some(&scope),
            &r,
            endpoint(),
            ExitAssignment::ProvenSameExit,
        ));
        assert_eq!(
            decision,
            TandemDnsRedirectDecision::Redirect {
                mode: TandemMode::ManagedRedirect,
                scope,
                service_address: Ipv4Addr::new(100, 64, 0, 9),
            }
        );
    }

    #[test]
    fn plain_managed_mode_never_redirects() {
        let phase = TandemTogglePhase::Active(TandemMode::Managed);
        let r = ready();
        let scope = all_scope();
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &r,
                endpoint(),
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::NoRedirect { reason: None }
        );
    }

    #[test]
    fn off_and_residue_produce_no_redirect() {
        let r = ready();
        let scope = all_scope();
        for (phase, reason) in [
            (TandemTogglePhase::Off, None),
            (TandemTogglePhase::ResidueError, Some(RC::Residue)),
        ] {
            assert_eq!(
                tandem_dns_redirect_decision(input(
                    &phase,
                    Some(&scope),
                    &r,
                    endpoint(),
                    ExitAssignment::ProvenSameExit,
                )),
                TandemDnsRedirectDecision::NoRedirect { reason }
            );
        }
    }

    #[test]
    fn prepare_and_drain_produce_no_redirect() {
        let r = ready();
        let scope = all_scope();
        for phase in [
            TandemTogglePhase::PreparingContained,
            TandemTogglePhase::Prepared,
            TandemTogglePhase::Draining,
        ] {
            assert_eq!(
                tandem_dns_redirect_decision(input(
                    &phase,
                    Some(&scope),
                    &r,
                    endpoint(),
                    ExitAssignment::ProvenSameExit,
                )),
                TandemDnsRedirectDecision::NoRedirect { reason: None },
                "phase {phase:?}"
            );
        }
    }

    #[test]
    fn draining_absence_does_not_open_plain_dns() {
        // The redirect's absence during draining is NOT an escape: the base
        // DNS-fail-closed posture still blocks. Assert the posture naming so
        // a caller cannot render "no rule" as "pass through".
        let phase = TandemTogglePhase::Draining;
        let r = ready();
        let scope = all_scope();
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &r,
                endpoint(),
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::NoRedirect { reason: None }
        );
    }

    #[test]
    fn runtime_contained_names_containment_not_open_escape() {
        let phase = TandemTogglePhase::RuntimeContained {
            reason: RC::ControlStaleWarning,
            desired_mode: TandemMode::ManagedRedirect,
        };
        let r = ready();
        let scope = all_scope();
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &r,
                endpoint(),
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::ContainNoRedirect {
                reason: RC::ControlStaleWarning
            }
        );
    }

    #[test]
    fn missing_scope_is_contained_not_redirect() {
        let phase = active_redirect();
        let r = ready();
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                None,
                &r,
                endpoint(),
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::ContainNoRedirect {
                reason: RC::SignedPolicyInvalid
            }
        );
    }

    #[test]
    fn unready_service_is_contained_not_redirect() {
        let phase = active_redirect();
        let scope = all_scope();
        let readiness = ReadinessObservation::NotReady(RC::ListenerUnready);
        let expected_reason = readiness
            .contain_reason()
            .unwrap_or(TandemReasonCode::RustydnsUnreachable);
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &readiness,
                endpoint(),
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::ContainNoRedirect {
                reason: expected_reason
            }
        );
    }

    #[test]
    fn stale_or_unauthenticated_readiness_contained() {
        let phase = active_redirect();
        let scope = all_scope();
        for (observation, reason) in [
            (ReadinessObservation::Stale, RC::ControlStaleWarning),
            (ReadinessObservation::Unauthenticated, RC::LocalAuthFailed),
        ] {
            let readiness = observation;
            assert_eq!(
                tandem_dns_redirect_decision(input(
                    &phase,
                    Some(&scope),
                    &readiness,
                    endpoint(),
                    ExitAssignment::ProvenSameExit,
                )),
                TandemDnsRedirectDecision::ContainNoRedirect { reason }
            );
        }
    }

    #[test]
    fn missing_or_offmesh_endpoint_contained() {
        let phase = active_redirect();
        let r = ready();
        let scope = all_scope();
        // No endpoint at all: refuse to translate.
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &r,
                None,
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::ContainNoRedirect {
                reason: RC::RustydnsUnreachable
            }
        );
        // Endpoint outside the mesh prefix: would DNAT off-mesh.
        let offmesh = Some(ManagedDnsEndpoint::new(Ipv4Addr::new(192, 168, 1, 5)));
        assert_eq!(
            tandem_dns_redirect_decision(input(
                &phase,
                Some(&scope),
                &r,
                offmesh,
                ExitAssignment::ProvenSameExit,
            )),
            TandemDnsRedirectDecision::ContainNoRedirect {
                reason: RC::AssignmentMismatch
            }
        );
    }

    #[test]
    fn unproven_exit_assignment_contained() {
        let phase = active_redirect();
        let r = ready();
        let scope = all_scope();
        for assignment in [ExitAssignment::ProvenMismatch, ExitAssignment::Unknown] {
            assert_eq!(
                tandem_dns_redirect_decision(input(
                    &phase,
                    Some(&scope),
                    &r,
                    endpoint(),
                    assignment,
                )),
                TandemDnsRedirectDecision::ContainNoRedirect {
                    reason: RC::AssignmentMismatch
                },
                "assignment {assignment:?}"
            );
        }
    }

    #[test]
    fn node_scope_passes_through_on_redirect() {
        // A listed client scope survives into the spec; the renderer uses it
        // to build the generation-scoped selected source set.
        let phase = active_redirect();
        let r = ready();
        let scope = TandemScope::NodeIds(vec!["node-b".into(), "node-a".into()]);
        let decision = tandem_dns_redirect_decision(input(
            &phase,
            Some(&scope),
            &r,
            endpoint(),
            ExitAssignment::ProvenSameExit,
        ));
        match decision {
            TandemDnsRedirectDecision::Redirect { scope: s, .. } => {
                assert_eq!(s, scope);
            }
            other => panic!("expected Redirect, got {other:?}"),
        }
    }

    /// Sanity: the decision never returns a redirect for any non-redirect
    /// phase, exhaustively over the state machine.
    #[test]
    fn never_redirects_outside_active_managed_redirect() {
        let r = ready();
        let scope = all_scope();
        let phases = [
            TandemTogglePhase::Off,
            TandemTogglePhase::PreparingContained,
            TandemTogglePhase::Prepared,
            TandemTogglePhase::Draining,
            TandemTogglePhase::RuntimeContained {
                reason: RC::ControlStaleWarning,
                desired_mode: TandemMode::Managed,
            },
            TandemTogglePhase::ResidueError,
            TandemTogglePhase::Active(TandemMode::Managed),
        ];
        for phase in &phases {
            assert!(
                !matches!(
                    tandem_dns_redirect_decision(input(
                        phase,
                        Some(&scope),
                        &r,
                        endpoint(),
                        ExitAssignment::ProvenSameExit,
                    )),
                    TandemDnsRedirectDecision::Redirect { .. }
                ),
                "phase {phase:?} must not redirect"
            );
        }
    }

    /// The reconcile state machine and the redirect decision agree: whatever
    /// `reconcile` holds active in managed_redirect, the decision redirects;
    /// whatever it contains, the redirect is contained.
    #[test]
    fn agrees_with_reconcile_active_managed_redirect() {
        let desired = DesiredPolicy::On(TandemDesiredOn {
            mode: TandemMode::ManagedRedirect,
            exit_node_id: "exit-1".into(),
            scope: all_scope(),
        });
        let output = crate::tandem_dns::reconcile(
            &TandemTogglePhase::Off,
            &desired,
            crate::tandem_dns::PolicyValidity::Fresh,
            &ReadinessObservation::Ready,
            true,
            ExitAssignment::ProvenSameExit,
            false,
            false,
        );
        if let TandemTogglePhase::Active(mode) = output.next {
            let phase = TandemTogglePhase::Active(mode);
            let readiness = ReadinessObservation::Ready;
            assert!(matches!(
                tandem_dns_redirect_decision(input(
                    &phase,
                    Some(&all_scope()),
                    &readiness,
                    endpoint(),
                    ExitAssignment::ProvenSameExit,
                )),
                TandemDnsRedirectDecision::Redirect { .. }
            ));
        }
    }
}
